/*
 * Automatically generated by jrpcgen 1.0.5 on 10/23/08 8:11 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package ganglia.xdr.v31x;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Ganglia_metadatadef implements XdrAble {
    public Ganglia_metric_id metric_id;
    public Ganglia_metadata_message metric;

    public Ganglia_metadatadef() {
    }

    public Ganglia_metadatadef(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        metric_id.xdrEncode(xdr);
        metric.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        metric_id = new Ganglia_metric_id(xdr);
        metric = new Ganglia_metadata_message(xdr);
    }

}
// End of Ganglia_metadatadef.java
