/*
 * Automatically generated by jrpcgen 1.0.5 on 10/23/08 8:11 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package ganglia.xdr.v31x;
/**
 * Enumeration (collection of constants).
 */
public interface Ganglia_msg_formats {

    public static final int gmetadata_full = 128;
    public static final int gmetric_ushort = 128+1;
    public static final int gmetric_short = 128+1+1;
    public static final int gmetric_int = 128+1+1+1;
    public static final int gmetric_uint = 128+1+1+1+1;
    public static final int gmetric_string = 128+1+1+1+1+1;
    public static final int gmetric_float = 128+1+1+1+1+1+1;
    public static final int gmetric_double = 128+1+1+1+1+1+1+1;
    public static final int gmetadata_request = 128+1+1+1+1+1+1+1+1;

}
// End of Ganglia_msg_formats.java
