/*
 * Automatically generated by jrpcgen 1.0.5 on 10/23/08 8:11 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package ganglia.xdr.v31x;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Ganglia_metric_id implements XdrAble {
    public String host;
    public String name;
    public boolean spoof;

    public Ganglia_metric_id() {
    }

    public Ganglia_metric_id(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeString(host);
        xdr.xdrEncodeString(name);
        xdr.xdrEncodeBoolean(spoof);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        host = xdr.xdrDecodeString();
        name = xdr.xdrDecodeString();
        spoof = xdr.xdrDecodeBoolean();
    }

}
// End of Ganglia_metric_id.java
