/*
 * Automatically generated by jrpcgen 1.0.5 on 10/23/08 8:11 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package ganglia.xdr.v31x;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Ganglia_metadata_msg implements XdrAble {
    public int id;
    public Ganglia_metadatadef gfull;
    public Ganglia_metadatareq grequest;

    public Ganglia_metadata_msg() {
    }

    public Ganglia_metadata_msg(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(id);
        switch ( id ) {
        case Ganglia_msg_formats.gmetadata_full:
            gfull.xdrEncode(xdr);
            break;
        case Ganglia_msg_formats.gmetadata_request:
            grequest.xdrEncode(xdr);
            break;
        default:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        id = xdr.xdrDecodeInt();
        switch ( id ) {
        case Ganglia_msg_formats.gmetadata_full:
            gfull = new Ganglia_metadatadef(xdr);
            break;
        case Ganglia_msg_formats.gmetadata_request:
            grequest = new Ganglia_metadatareq(xdr);
            break;
        default:
            break;
        }
    }

}
// End of Ganglia_metadata_msg.java
