/*
 * Automatically generated by jrpcgen 1.0.5 on 10/23/08 8:11 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package ganglia.xdr.v31x;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Ganglia_value_msg implements XdrAble {
    public int id;
    public Ganglia_gmetric_ushort gu_short;
    public Ganglia_gmetric_short gs_short;
    public Ganglia_gmetric_int gs_int;
    public Ganglia_gmetric_uint gu_int;
    public Ganglia_gmetric_string gstr;
    public Ganglia_gmetric_float gf;
    public Ganglia_gmetric_double gd;

    public Ganglia_value_msg() {
    }

    public Ganglia_value_msg(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(id);
        switch ( id ) {
        case Ganglia_msg_formats.gmetric_ushort:
            gu_short.xdrEncode(xdr);
            break;
        case Ganglia_msg_formats.gmetric_short:
            gs_short.xdrEncode(xdr);
            break;
        case Ganglia_msg_formats.gmetric_int:
            gs_int.xdrEncode(xdr);
            break;
        case Ganglia_msg_formats.gmetric_uint:
            gu_int.xdrEncode(xdr);
            break;
        case Ganglia_msg_formats.gmetric_string:
            gstr.xdrEncode(xdr);
            break;
        case Ganglia_msg_formats.gmetric_float:
            gf.xdrEncode(xdr);
            break;
        case Ganglia_msg_formats.gmetric_double:
            gd.xdrEncode(xdr);
            break;
        default:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        id = xdr.xdrDecodeInt();
        switch ( id ) {
        case Ganglia_msg_formats.gmetric_ushort:
            gu_short = new Ganglia_gmetric_ushort(xdr);
            break;
        case Ganglia_msg_formats.gmetric_short:
            gs_short = new Ganglia_gmetric_short(xdr);
            break;
        case Ganglia_msg_formats.gmetric_int:
            gs_int = new Ganglia_gmetric_int(xdr);
            break;
        case Ganglia_msg_formats.gmetric_uint:
            gu_int = new Ganglia_gmetric_uint(xdr);
            break;
        case Ganglia_msg_formats.gmetric_string:
            gstr = new Ganglia_gmetric_string(xdr);
            break;
        case Ganglia_msg_formats.gmetric_float:
            gf = new Ganglia_gmetric_float(xdr);
            break;
        case Ganglia_msg_formats.gmetric_double:
            gd = new Ganglia_gmetric_double(xdr);
            break;
        default:
            break;
        }
    }

}
// End of Ganglia_value_msg.java
