/*
 * Automatically generated by jrpcgen 1.0.5 on 3/30/08 8:06 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package ganglia.xdr.v30x;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Ganglia_gmetric_message implements XdrAble {
    public String type;
    public String name;
    public String value;
    public String units;
    public int slope;
    public int tmax;
    public int dmax;

    public Ganglia_gmetric_message() {
    }

    public Ganglia_gmetric_message(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeString(type);
        xdr.xdrEncodeString(name);
        xdr.xdrEncodeString(value);
        xdr.xdrEncodeString(units);
        xdr.xdrEncodeInt(slope);
        xdr.xdrEncodeInt(tmax);
        xdr.xdrEncodeInt(dmax);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        type = xdr.xdrDecodeString();
        name = xdr.xdrDecodeString();
        value = xdr.xdrDecodeString();
        units = xdr.xdrDecodeString();
        slope = xdr.xdrDecodeInt();
        tmax = xdr.xdrDecodeInt();
        dmax = xdr.xdrDecodeInt();
    }

}
// End of Ganglia_gmetric_message.java
