/*
 * Automatically generated by jrpcgen 1.0.5 on 3/30/08 8:06 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package ganglia.xdr.v30x;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Ganglia_25metric implements XdrAble {
    public int key;
    public String name;
    public int tmax;
    public int type;
    public String units;
    public String slope;
    public String fmt;
    public int msg_size;

    public Ganglia_25metric() {
    }

    public Ganglia_25metric(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(key);
        xdr.xdrEncodeString(name);
        xdr.xdrEncodeInt(tmax);
        xdr.xdrEncodeInt(type);
        xdr.xdrEncodeString(units);
        xdr.xdrEncodeString(slope);
        xdr.xdrEncodeString(fmt);
        xdr.xdrEncodeInt(msg_size);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        key = xdr.xdrDecodeInt();
        name = xdr.xdrDecodeString();
        tmax = xdr.xdrDecodeInt();
        type = xdr.xdrDecodeInt();
        units = xdr.xdrDecodeString();
        slope = xdr.xdrDecodeString();
        fmt = xdr.xdrDecodeString();
        msg_size = xdr.xdrDecodeInt();
    }

}
// End of Ganglia_25metric.java
