/*
 * Automatically generated by jrpcgen 1.0.5 on 3/30/08 8:06 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package ganglia.xdr.v30x;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Ganglia_spoof_message implements XdrAble {
    public Ganglia_spoof_header spheader;
    public Ganglia_gmetric_message gmetric;

    public Ganglia_spoof_message() {
    }

    public Ganglia_spoof_message(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        spheader.xdrEncode(xdr);
        gmetric.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        spheader = new Ganglia_spoof_header(xdr);
        gmetric = new Ganglia_gmetric_message(xdr);
    }

}
// End of Ganglia_spoof_message.java
