/*
 * Automatically generated by jrpcgen 1.0.5 on 3/30/08 8:06 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package ganglia.xdr.v30x;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Ganglia_message implements XdrAble {
    public int id;
    public Ganglia_gmetric_message gmetric;
    public Ganglia_spoof_message spmetric;
    public Ganglia_spoof_header spheader;
    public short u_short1;
    public int u_int1;
    public String str;
    public float f;
    public double d;

    public Ganglia_message() {
    }

    public Ganglia_message(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(id);
        switch ( id ) {
        case Ganglia_message_formats.metric_user_defined:
            gmetric.xdrEncode(xdr);
            break;
        case Ganglia_message_formats.spoof_metric:
            spmetric.xdrEncode(xdr);
            break;
        case Ganglia_message_formats.spoof_heartbeat:
            spheader.xdrEncode(xdr);
            break;
        case Ganglia_message_formats.metric_cpu_num:
            xdr.xdrEncodeShort(u_short1);
            break;
        case Ganglia_message_formats.metric_cpu_speed:
        case Ganglia_message_formats.metric_mem_total:
        case Ganglia_message_formats.metric_swap_total:
        case Ganglia_message_formats.metric_boottime:
        case Ganglia_message_formats.metric_sys_clock:
        case Ganglia_message_formats.metric_proc_run:
        case Ganglia_message_formats.metric_proc_total:
        case Ganglia_message_formats.metric_mem_free:
        case Ganglia_message_formats.metric_mem_shared:
        case Ganglia_message_formats.metric_mem_buffers:
        case Ganglia_message_formats.metric_mem_cached:
        case Ganglia_message_formats.metric_swap_free:
        case Ganglia_message_formats.metric_heartbeat:
        case Ganglia_message_formats.metric_mtu:
        case Ganglia_message_formats.metric_mem_arm:
        case Ganglia_message_formats.metric_mem_rm:
        case Ganglia_message_formats.metric_mem_avm:
        case Ganglia_message_formats.metric_mem_vm:
            xdr.xdrEncodeInt(u_int1);
            break;
        case Ganglia_message_formats.metric_machine_type:
        case Ganglia_message_formats.metric_os_name:
        case Ganglia_message_formats.metric_os_release:
        case Ganglia_message_formats.metric_gexec:
        case Ganglia_message_formats.metric_location:
            xdr.xdrEncodeString(str);
            break;
        case Ganglia_message_formats.metric_cpu_user:
        case Ganglia_message_formats.metric_cpu_nice:
        case Ganglia_message_formats.metric_cpu_system:
        case Ganglia_message_formats.metric_cpu_idle:
        case Ganglia_message_formats.metric_cpu_aidle:
        case Ganglia_message_formats.metric_load_one:
        case Ganglia_message_formats.metric_load_five:
        case Ganglia_message_formats.metric_load_fifteen:
        case Ganglia_message_formats.metric_bytes_in:
        case Ganglia_message_formats.metric_bytes_out:
        case Ganglia_message_formats.metric_pkts_in:
        case Ganglia_message_formats.metric_pkts_out:
        case Ganglia_message_formats.metric_part_max_used:
        case Ganglia_message_formats.metric_cpu_wio:
        case Ganglia_message_formats.metric_bread_sec:
        case Ganglia_message_formats.metric_bwrite_sec:
        case Ganglia_message_formats.metric_lread_sec:
        case Ganglia_message_formats.metric_lwrite_sec:
        case Ganglia_message_formats.metric_rcache:
        case Ganglia_message_formats.metric_wcache:
        case Ganglia_message_formats.metric_phread_sec:
        case Ganglia_message_formats.metric_phwrite_sec:
        case Ganglia_message_formats.metric_cpu_intr:
        case Ganglia_message_formats.metric_cpu_sintr:
            xdr.xdrEncodeFloat(f);
            break;
        case Ganglia_message_formats.metric_disk_total:
        case Ganglia_message_formats.metric_disk_free:
            xdr.xdrEncodeDouble(d);
            break;
        default:
            break;
        }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        id = xdr.xdrDecodeInt();
        switch ( id ) {
        case Ganglia_message_formats.metric_user_defined:
            gmetric = new Ganglia_gmetric_message(xdr);
            break;
        case Ganglia_message_formats.spoof_metric:
            spmetric = new Ganglia_spoof_message(xdr);
            break;
        case Ganglia_message_formats.spoof_heartbeat:
            spheader = new Ganglia_spoof_header(xdr);
            break;
        case Ganglia_message_formats.metric_cpu_num:
            u_short1 = xdr.xdrDecodeShort();
            break;
        case Ganglia_message_formats.metric_cpu_speed:
        case Ganglia_message_formats.metric_mem_total:
        case Ganglia_message_formats.metric_swap_total:
        case Ganglia_message_formats.metric_boottime:
        case Ganglia_message_formats.metric_sys_clock:
        case Ganglia_message_formats.metric_proc_run:
        case Ganglia_message_formats.metric_proc_total:
        case Ganglia_message_formats.metric_mem_free:
        case Ganglia_message_formats.metric_mem_shared:
        case Ganglia_message_formats.metric_mem_buffers:
        case Ganglia_message_formats.metric_mem_cached:
        case Ganglia_message_formats.metric_swap_free:
        case Ganglia_message_formats.metric_heartbeat:
        case Ganglia_message_formats.metric_mtu:
        case Ganglia_message_formats.metric_mem_arm:
        case Ganglia_message_formats.metric_mem_rm:
        case Ganglia_message_formats.metric_mem_avm:
        case Ganglia_message_formats.metric_mem_vm:
            u_int1 = xdr.xdrDecodeInt();
            break;
        case Ganglia_message_formats.metric_machine_type:
        case Ganglia_message_formats.metric_os_name:
        case Ganglia_message_formats.metric_os_release:
        case Ganglia_message_formats.metric_gexec:
        case Ganglia_message_formats.metric_location:
            str = xdr.xdrDecodeString();
            break;
        case Ganglia_message_formats.metric_cpu_user:
        case Ganglia_message_formats.metric_cpu_nice:
        case Ganglia_message_formats.metric_cpu_system:
        case Ganglia_message_formats.metric_cpu_idle:
        case Ganglia_message_formats.metric_cpu_aidle:
        case Ganglia_message_formats.metric_load_one:
        case Ganglia_message_formats.metric_load_five:
        case Ganglia_message_formats.metric_load_fifteen:
        case Ganglia_message_formats.metric_bytes_in:
        case Ganglia_message_formats.metric_bytes_out:
        case Ganglia_message_formats.metric_pkts_in:
        case Ganglia_message_formats.metric_pkts_out:
        case Ganglia_message_formats.metric_part_max_used:
        case Ganglia_message_formats.metric_cpu_wio:
        case Ganglia_message_formats.metric_bread_sec:
        case Ganglia_message_formats.metric_bwrite_sec:
        case Ganglia_message_formats.metric_lread_sec:
        case Ganglia_message_formats.metric_lwrite_sec:
        case Ganglia_message_formats.metric_rcache:
        case Ganglia_message_formats.metric_wcache:
        case Ganglia_message_formats.metric_phread_sec:
        case Ganglia_message_formats.metric_phwrite_sec:
        case Ganglia_message_formats.metric_cpu_intr:
        case Ganglia_message_formats.metric_cpu_sintr:
            f = xdr.xdrDecodeFloat();
            break;
        case Ganglia_message_formats.metric_disk_total:
        case Ganglia_message_formats.metric_disk_free:
            d = xdr.xdrDecodeDouble();
            break;
        default:
            break;
        }
    }

}
// End of Ganglia_message.java
