/*
 * Automatically generated by jrpcgen 1.0.5 on 3/30/08 8:06 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package ganglia.xdr;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Ganglia_spoof_header implements XdrAble {
    public String spoofName;
    public String spoofIP;

    public Ganglia_spoof_header() {
    }

    public Ganglia_spoof_header(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeString(spoofName);
        xdr.xdrEncodeString(spoofIP);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        spoofName = xdr.xdrDecodeString();
        spoofIP = xdr.xdrDecodeString();
    }

}
// End of Ganglia_spoof_header.java
