/*
 * Automatically generated by jrpcgen 1.0.5 on 3/30/08 8:06 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package ganglia.xdr;
/**
 * Enumeration (collection of constants).
 */
public interface Ganglia_value_types {

    public static final int GANGLIA_VALUE_UNKNOWN = 0;
    public static final int GANGLIA_VALUE_STRING = 0+1;
    public static final int GANGLIA_VALUE_UNSIGNED_SHORT = 0+1+1;
    public static final int GANGLIA_VALUE_SHORT = 0+1+1+1;
    public static final int GANGLIA_VALUE_UNSIGNED_INT = 0+1+1+1+1;
    public static final int GANGLIA_VALUE_INT = 0+1+1+1+1+1;
    public static final int GANGLIA_VALUE_FLOAT = 0+1+1+1+1+1+1;
    public static final int GANGLIA_VALUE_DOUBLE = 0+1+1+1+1+1+1+1;

}
// End of Ganglia_value_types.java
