/*
 * Automatically generated by jrpcgen 1.0.5 on 3/30/08 8:06 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package ganglia.xdr;
/**
 * Enumeration (collection of constants).
 */
public interface Ganglia_message_formats {

    public static final int metric_user_defined = 0;
    public static final int metric_cpu_num = 0+1;
    public static final int metric_cpu_speed = 0+1+1;
    public static final int metric_mem_total = 0+1+1+1;
    public static final int metric_swap_total = 0+1+1+1+1;
    public static final int metric_boottime = 0+1+1+1+1+1;
    public static final int metric_sys_clock = 0+1+1+1+1+1+1;
    public static final int metric_machine_type = 0+1+1+1+1+1+1+1;
    public static final int metric_os_name = 0+1+1+1+1+1+1+1+1;
    public static final int metric_os_release = 0+1+1+1+1+1+1+1+1+1;
    public static final int metric_cpu_user = 0+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_cpu_nice = 0+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_cpu_system = 0+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_cpu_idle = 0+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_cpu_aidle = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_load_one = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_load_five = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_load_fifteen = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_proc_run = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_proc_total = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_mem_free = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_mem_shared = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_mem_buffers = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_mem_cached = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_swap_free = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_gexec = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_heartbeat = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_mtu = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_location = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_bytes_out = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_bytes_in = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_pkts_in = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_pkts_out = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_disk_total = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_disk_free = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_part_max_used = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_cpu_wio = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_bread_sec = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_bwrite_sec = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_lread_sec = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_lwrite_sec = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_rcache = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_wcache = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_phread_sec = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_phwrite_sec = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_cpu_intr = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_cpu_sintr = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_mem_arm = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_mem_rm = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_mem_avm = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int metric_mem_vm = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int GANGLIA_NUM_25_METRICS = 0+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1;
    public static final int spoof_metric = 4096;
    public static final int spoof_heartbeat = 4097;

}
// End of Ganglia_message_formats.java
